package com.example.myapplication12.constant

import com.example.myapplication12.view.activity.MainActivity

lateinit var MAIN:MainActivity

const val NUMBER_BACKGROUND_IMAGE = "NUMBER_BACKGROUND_IMAGE"
const val APP_PREFERENCES = "APP_PREFERENCES"
const val COUNT_INPUT_IN_APP = "COUNT_INPUT_IN_APP"
const val GAME = "GAME"
const val GAME_COMPLEXITY = "GAME_COMPLEXITY"
const val COMPLEXITY_EASY = "COMPLEXITY_EASY"
const val COMPLEXITY_MIDDLE = "COMPLEXITY_MIDDLE"
const val COMPLEXITY_HARD = "COMPLEXITY_HARD"
const val GAME_FOOTBALL = "GAME_FOOTBALL"
const val GAME_BASKETBALL = "GAME_BASKETBALL"
const val GAME_HOCKEY = "GAME_HOCKEY"
const val CURRENT_RESULT = "CURRENT_RESULT"
const val TIME_SPENT = "TIME_SPENT"
const val ID = "ID"

const val RECORD_FOOTBALL_EASY = "RECORD_FOOTBALL_EASY"
const val RECORD_FOOTBALL_MIDDLE = "RECORD_FOOTBALL_MIDDLE"
const val RECORD_FOOTBALL_HARD = "RECORD_FOOTBALL_HARD"
const val RECORD_BASKET_EASY = "RECORD_BASKET_EASY"
const val RECORD_BASKET_MIDDLE = "RECORD_BASKET_MIDDLE"
const val RECORD_BASKET_HARD = "RECORD_BASKET_HARD"
const val RECORD_HOCKEY_EASY = "RECORD_HOCKEY_EASY"
const val RECORD_HOCKEY_MIDDLE = "RECORD_HOCKEY_MIDDLE"
const val RECORD_HOCKEY_HARD = "RECORD_HOCKEY_HARD"